name: Comment GIF 🤡
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  giphy-generator:
    name: Comment GIF after /giphy command 🤡
    runs-on: ubuntu-latest
    steps:
      - name: GIPHY generator 🤡
        id: giphy_generator
        uses: iamhughes/giphy-generator@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
        with:
          rating: "g"
          lang: "en"
